--- #YAML:1.0
name:                Test-More-Behaviour
version:             0.4.0
abstract:            ~
license:             ~
author:              
    - Matthew Boston <matthew.boston@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Term::ANSIColor:               0
    Test::More:                    0
    version:                       0.77
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
